### ISSUE TITLE
Restart clipper containers and app containers on server reboot

### ISSUE THREAD

**Issue by rmdort** [ucbrise/clipper#155]
Upon server reboot, can we restart

1. Clipper containers - I think this can be by adding `restart:always` to `docker-compose.yaml` file
2. Model containers - If a model is currently active, can we restart the specific containers. Not sure how this can be done.

Can we also move redis storage to a persistent volume in docker-compose. I think i saw a discussion about this on your Jira, but the issue was closed.

````
services:
  redis:
     volumes:
          - redisdata:/data
````
