### ISSUE TITLE
Improved metrics and monitoring infrastructure

### ISSUE THREAD

**Issue by dcrankshaw** [ucbrise/clipper#339]
Clipper already tracks some basic internal performance metrics, but these are tracked on an ad-hoc basis and not aggregated. As we expand support for running larger Clipper clusters with multiple query frontend replicas, we need better metrics tracking and monitoring. Furthermore, we will be expanding to provide statistical performance monitoring early next year and will want to integrate these into the existing metrics tracking infrastructure. Because this requires fleshing out some real architectural questions and expanding our set of dependencies, this feature has a separate design document associated with it.

[Design Doc (WIP)](https://docs.google.com/a/berkeley.edu/document/d/10whRxCc97gOJl4j2lY6R-v7cI_ZoAMVcNGPG_9oj6iY/edit?usp=sharing)

**Comment by simon-mo** [comment]
#348 gives a MVP. I'll start working on a second PR that includes:
- [x] Allow port specification for Prometheus container port forwarding (to avoid clash, at least).
- [x] Add Monitor Example/Tutorial in example folder. Include a default visualization with Grafana section in it. [Grafana Docker](http://docs.grafana.org/installation/docker/)
- [x] Set up "configuration" like metric specification from a file `metric_config.yaml` or `metric_config.py` or `metric_config.json` looks very roughly like the following:
```yaml
# Four Metric Type {Counter | Gauge | Histogram | Summary}, 
# see: https://prometheus.io/docs/concepts/metric_types/

Model Container:
  pred_count:
    - type: Counter
    - description: The number of prediction made in this model container
  
  parse_time_ms:
    - type: Histogram
    - decription: The time in ms takes to parse RPC call from query frontend.

Query Frontend:
  query_count:
    - type: Counter
    - description: The number of prediction make in current query frontend


# Redis:
#   Redis metrics is exproted by [Redis Exporter](https://github.com/oliver006/redis_exporter)
#   It export the default redis [info](https://redis.io/commands/info)
#   BUT: it can monitors metrics for a specific key too.
Redis:
  - some_key_1
  - some_key_2

```
I proposed this to have a record of all the metrics we are collecting documented in one place (located in `$CLIPPER_ROOT/monitoring`), so that in the future it will be easy to add more metrics without changing much of the code or even without the knowledge how the metric monitoring system is setup. 

- [x] Metrics for model container:
```markdown
- Latencies
     - End-to-end
     - User’s predict function
- Counts:
     - Number of predictions
- Rates
     - Predictions per second
```
Rates is done by prometheus aggregation function.
